[build-system]

requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]

name = "caddrive"
version = "0.0.1"
dependencies = [
  "pandas",
  "requests-toolbelt"
]
requires-python = ">= 3.9"
authors = [
  { name = "Christian Zehetner", email = "christian.zehetner@fh-wels.at" },
  { name = "Georg Hackenberg",   email = "georg.hackenberg@fh-wels.at" }
]
maintainers = [
  { name = "Christian Zehetner", email = "christian.zehetner@fh-wels.at" },
  { name = "Georg Hackenberg",   email = "georg.hackenberg@fh-wels.at" }
]
description = "Tools for creating CodeAster models from LDraw models"
readme = "README.md"
license = { file = "LICENSE.md" }

[project.urls]

Homepage = "https://github.com/ghackenberg/caddrive"