services:
     
  leofea:
    build: ./leofea
    image: caddrive/leofea:latest
    command: python -u main.py --debug
    volumes:
      - ./leofea:/app
    ports:
      - 5000:5000

  codeaster:
    build: ./codeaster
    image: caddrive/codeaster:latest
    command: python -u main.py --debug
    volumes:
      - ./codeaster:/app
    ports:
      - 5001:5000

  # openfoam-com:
  #   build: ./openfoam-com
  #   image: caddrive/openfoam-com:latest
  #   command: python -u main.py --debug
  #   volumes:
  #     - ./openfoam-com:/root
  #   ports:
  #     - 5002:5000

  # openfoam-org:
  #   build: ./openfoam-org
  #   image: caddrive/openfoam-org:latest
  #   command: python -u main.py --debug
  #   volumes:
  #     - ./openfoam-org:/root
  #   ports:
  #     - 5003:5000

  paraview:
    build: ./paraview
    image: caddrive/paraview:latest
    command: python -u main.py --debug
    volumes:
      - ./paraview:/app
    ports:
      - 5004:5000
      