name: Static Code Analysis

on:
  push:
    branches: [ master ]
    paths:
      - packages/**
      - .github/workflows/static-code-analysis.yml
  pull_request:
    branches: [ master ]
    paths:
      - packages/**
      - .github/workflows/static-code-analysis.yml

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout GIT repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: sudo apt-get install -y libxi-dev libgl-dev
      - name: Update NPM
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm install
      - name: Re-install opencascade.js@beta dependency
        run: npm install -w packages/frontend opencascade.js@beta
      - name: Build sources
        run: npm run build
      - name: Lint sources
        run: npm run lint